FROM debian:jessie

RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	apt-get -y update && \
	apt-get -y install --no-install-recommends \
		apt-transport-https \
		ca-certificates \
	&& \
	apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 && \
	echo 'deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main' > /etc/apt/sources.list.d/passenger.list && \
	apt-get -y update && \
	apt-get -y upgrade && \
	apt-get -y install --no-install-recommends \
		build-essential \
		git-core \
		libicu-dev \
		nginx-extras \
		ruby \
		ruby-dev \
		zlib1g-dev \
	&& \
	apt-get -y install \
		passenger \
	&& \
	gem install --no-ri --no-rdoc \
		'gollum:<5' \
		github-markdown \
	&& \
	apt-get -y remove \
		apt-transport-https \
		build-essential \
		ruby-dev \
		zlib1g-dev \
	&& \
	apt-get -y autoremove && \
	apt-get clean && \
	rm /etc/apt/sources.list.d/passenger.list && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	:

VOLUME /wiki
WORKDIR /wiki
EXPOSE 80

ENV GOLLUM_DIR=/wiki
CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]

RUN \
	groupadd -g 1000 gollum && \
	useradd -u 1000 -g gollum gollum && \
	chown -R gollum. /wiki && \
	:

COPY gollum /etc/nginx/sites-available/
COPY nginx.conf /etc/nginx/
COPY config.ru /opt/gollum/

RUN \
	ln -s /etc/nginx/sites-available/gollum /etc/nginx/sites-enabled/ && \
	rm /etc/nginx/sites-enabled/default && \
	passenger-config validate-install && \
	:
