name: docker-image

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '* * 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Ansible Docs Image
        id: docker_build_ansible_docs
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/ansible-docs:latest
          context: ./ansible-docs
          file: ./ansible-docs/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_ansible_docs.outputs.digest }}
