name: ipecho

on:
  push:
    paths:
      - 'ipecho/**'
      - '.github/workflows/ipecho.yml'
  schedule:
    - cron: '40 2 1 * *'

jobs:
  docker_ipecho:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Build and push ipecho image
        id: docker_build_push_ipecho
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: joelnb/ipecho:latest
          context: ./ipecho
          file: ./ipecho/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_push_ipecho.outputs.digest }}
      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: joelnb/ipecho:latest
          fail-build: false
        if: github.ref == 'refs/heads/master'
