name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
    - uses: actions/checkout@v5
    - name: hadolint
      run: hadolint ./**/*Dockerfile*
