name: Renovate

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 4 * * *'

jobs:
  main:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Renovate
        uses: djiit/action-renovate@master
        with:
          args: >-
            ${{ github.repository }}
            --onboarding=false
            --require-config=false
            --semantic-commits=true
            --log-level=debug
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
