name: ssh

on:
  push:
    paths:
      - 'ssh/**'
      - '.github/workflows/ssh.yml'
  schedule:
    - cron: '0 2 1 * *'

jobs:
  docker_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Build and push ssh image (latest)
        id: docker_build_push_ssh
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: joelnb/ssh:latest
          context: ./ssh
          file: ./ssh/Dockerfile
      - name: Image digest (latest)
        run: echo ${{ steps.docker_build_push_ssh.outputs.digest }}
      - name: Scan image (latest)
        uses: anchore/scan-action@v3
        with:
          image: joelnb/ssh:latest
          fail-build: false
        if: github.ref == 'refs/heads/master'

      - name: Build and push ssh image (trusty)
        id: docker_build_push_ssh_trusty
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: joelnb/ssh:trusty
          context: ./ssh/trusty
          file: ./ssh/trusty/Dockerfile
      - name: Image digest (trusty)
        run: echo ${{ steps.docker_build_push_ssh_trusty.outputs.digest }}
      - name: Scan image (trusty)
        uses: anchore/scan-action@v3
        with:
          image: joelnb/ssh:trusty
          fail-build: false
        if: github.ref == 'refs/heads/master'

      - name: Build and push ssh image (xenial)
        id: docker_build_push_ssh_xenial
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: joelnb/ssh:xenial
          context: ./ssh/xenial
          file: ./ssh/xenial/Dockerfile
      - name: Image digest (xenial)
        run: echo ${{ steps.docker_build_push_ssh_xenial.outputs.digest }}
      - name: Scan image (xenial)
        uses: anchore/scan-action@v3
        with:
          image: joelnb/ssh:xenial
          fail-build: false
        if: github.ref == 'refs/heads/master'
